---
- name: install jdk maven and build app 
  hosts: build
  become: yes

  tasks:
    - name: Enshure maven and java is present
      apt: 
        name: 
        - maven
        - default-jdk
        state: present 

#    - name: create directory
#      file:
#        path: /root/app
#        state: directory

    - name: clone app repo 
      ansible.builtin.git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /root/app 
      clone: yes

    - name: build war file
      command: mvn build . arg1
      args:
        chdir: /root/app/boxfuse-sample-java-war-hello

    - name: copy artifact to mastee
      synchronize: 
      - src: root@:/target/hello-1.0.war 
      - dest: root@18.221.81.227:/root/hello-1.0.war"

- name: install tomcat to prod
  hosts: prod
  become: yes

  tasks:
    - name: install tomcat and jre
      apt:
        name: 
        - tomcat9
        - default-jre
        state: present 

    - name: copy artifact from master
      shell: "rsync -v root@18.221.81.227:/root/hello-1.0.war /var/lib/tomcat9/webapps/hello-1.0.war"

   