---
- name: install java and maven
  hosts: build
  become: yes

  tasks:
    - name: install maven
      apt: 
        name: maven
        state: present 

    - name: install java
      apt: 
        name: default-jdk
        state: present 

    - name: install git
      apt:
        name: git
        state: present 

    - name: install rsync
      apt:
        name: rsync
        state: present 

    - name: create directory
      file:
        path: /app
        state: directory

    - name: clone app repo 
      command: git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git arg1
      args:
        chdir: /app 

    - name: build war file
      command: mvn build . arg1
      args:
        chdir: /boxfuse-sample-java-war-hello

    - name: copy artifact
      shell: "rsync -v /target/hello-1.0.war root@18.221.81.227:/root/hello-1.0.war"

- name: install tomcat to prod
  hosts: prod
  become: yes

  tasks:
    - name: install tomcat
      apt:
        name: tomcat9
        state: present 

    - name: install java
      apt:
        name: default-jdk
        state: present

    - name: install rsync
      apt: 
        name: rsync
        state: present 

    - name: copy artifact from master
      shell: "rsync -v root@18.221.81.227:/root/hello-1.0.war /var/lib/tomcat9/webapps/hello-1.0.war"

   