---
- name: install java and maven
  hosts: build
  become: yes

  tasks:
    - name: install maven
      apt: 
        name: maven
        state: present 

    - name: install java
      apt: 
        name: default-jdk
        state: present 

- name: install tomcat to prod
  hosts: prod
  become: yes

  tasks:
    - name: install tomcat
      apt:
        name: tomcat9
        state: present 

    - name: install java
      apt:
        name: default-jdk
        state: present 

    - name: start service tomcat 
      service:
        name: tomcat
        state: started
        enabled: true
        

       