---
- name: install java and maven
  hosts: build
  become: yes

  tasks:
    - name: install maven
      apt: 
        name: maven
        state: present 

    - name: install java
      apt: 
        name: default-jdk
        state: present 

       