---
- name: install jdk maven and build app 
  hosts: build
  become: yes

  tasks:
    - name: Enshure maven and java is present
      apt: 
        name: ['maven', 'default-jdk', 'tree'] 
        state: present

    - name: enshure empty directory for git clone
      file:
        path: /app
        state: absent


    - name: clone app repo 
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /app 
        clone: yes

    - name: build war file
      command: mvn package 
      args:
        chdir: /app

    - name: copy artifact to master
      synchronize: 
        mode: pull
        src: /app/target/hello-1.0.war 
        dest: /root/hello-1.0.war

- name: install tomcat to prod
  hosts: prod
  become: yes

  tasks:
    - name: install tomcat and jre to prod
      apt: 
        name: ['maven', 'default-jre']
        state: present

    - name: copy artifact from master
      synchronize: 
        mode: push
        src: /root/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/hello-1.0.war

   