---
- name: install java and maven
  hosts: build
  become: yes

  tasks:
    - name: install maven
      apt: 
        name: maven
        state: present 

    - name: install java
      apt: 
        name: default-jdk
        state: present 

    - name: install git
      apt:
        name: git
        state: present 

    - name: install rsync
      apt:
        name: rsync
        state: present 

    - name: copy sourse for build
      shell: "mkdir /app && cd app"
      
    - name: git clone
      shell: "git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git && cd boxfuse-sample-java-war-hello"  

    - name: build war
      shell: "mvn build"

    - name: copy artifact
      shell: "rsync -v /target/hello-1.0.war root@18.217.245.217:/root/hello-1.0.war"

- name: install tomcat to prod
  hosts: prod
  become: yes

  tasks:
    - name: install tomcat
      apt:
        name: tomcat9
        state: present 

    - name: install java
      apt:
        name: default-jdk
        state: present

    - name: install rsync
      apt: 
        name: rsync
        state: present 

    - name: copy artifact from master
      shell: "rsync -v root@18.217.245.217:/root/hello-1.0.war /var/lib/tomcat9/webapps/hello-1.0.war"

   