---
- name: install jdk maven and build app 
  hosts: build
  become: yes

  tasks:
    - name: Enshure maven and java is present
      apt: name={{ item }} state=present
      with_items:
        - maven
        - default-jdk
        - tree

    - name: enshure empty directory for git clone
      file:
        path: /root/app
        state: absent


    - name: clone app repo 
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /root/app 
        clone: yes

    - name: show me dir structure
      shell: "tree"

    - name: build war file
      command: mvn package arg1
      args:
        chdir: /root/app/boxfuse-sample-java-war-hello/

    - name: copy artifact to master
      synchronize: 
        src: /root/app/boxfuse-sample-java-war-hello/target/hello-1.0.war 
        dest: /root/hello-1.0.war

- name: install tomcat to prod
  hosts: prod
  become: yes

  tasks:
    - name: install tomcat and jre to prod
      apt: name={{ item }} state=present
      with_items:
        - maven
        - default-jdk

    - name: copy artifact from master
      synchronize: 
        src: /root/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/hello-1.0.war

   